# Generated by Django 3.1.4 on 2021-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210124_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
